### ISSUE TITLE
Evaluate APIs for live option data

### ISSUE THREAD

**Issue by joe-wojniak** [flooidio/tradebot#4]
TDAmeritrade API 
https://developer.tdameritrade.com/apis
e*Trade API           
https://apisb.etrade.com/docs/api/market/api-market-v1.html#/definition/getOptionChains
Options Route
https://optionsroute.com/
https://optionsroute.com/total-access
tradier brokerage
https://brokerage.tradier.com/pricing

Article Top 4 Stock and Options Market Data APIs in 2021
https://techbum.io/best-free-api-for-stock-market-data/

**Comment by joe-wojniak** [comment]
### TDAmeritrade       (+++)
* option chain & strategy chain, place orders, price history, quotes, transaction history
### e*Trade                (+++)
* option chain, option expire dates
### Options Route       (---)
_(commission-free options trading, $0.50/contract, $39.95 monthly fee)_
* no details could be found on website
### tradier brokerage  (---)
_($0.35/contract)_
* $9 per options assignment/exercise

**Comment by fredyvilla** [comment]
I use TOS so I can start evaluating TDAmeritrade.

**Comment by joe-wojniak** [comment]
Ok, I also use TOS.  I have written a script to access some of TDAmeritrade's api.  Navigating OAUTH2 was the difficult part for me.  I'll post the code to /tdameritrade
