### ISSUE TITLE
Use Discord or Slack for Team communication?

### ISSUE THREAD

**Issue by joe-wojniak** [flooidio/tradebot#5]
Discord is a chat app that I've seen being used for team communications.
https://discord.com/brand-new
Slack might be another option.
https://slack.com/

**Comment by fredyvilla** [comment]
Let's use discord. Slack is probably better but I use it at work and may get confusing switching workspaces.

**Comment by fredyvilla** [comment]
Here is the link: https://discord.gg/VwpwgSbSCP
